### ISSUE TITLE
Support for OneTrustSDK version 202307.1.0

### ISSUE THREAD

**Issue by alvinyu2003** [mparticle-integrations/mparticle-apple-integration-onetrust#10]
Hello mparticle-integrations team,

Firstly, thank you for the hard work on maintaining the `mparticle-apple-integration-onetrust` repository.

I'd like to bring to your attention that there's a newer version of the OneTrustSDK available on the OneTrust dashboard, specifically version `202307.1.0`. Our project heavily depends on the latest security and functionality updates from the OneTrust SDK, and it would be beneficial for us (and likely other users) if the `mparticle-apple-integration-onetrust` integration supports this latest version.

**Specifics:**

- **Current Supported Version:** 202302.1.0
- **Requested Version:** 202307.1.0

**Potential benefits:**

1. **Updated Functionality:** Leveraging the latest functionalities provided by the new version.
2. **Security Improvements:** Staying up-to-date with security patches and improvements.
3. **Bug Fixes:** Mitigation of any known issues that have been addressed in the newer version.

We understand that updating integrations can be time-consuming, and we appreciate any efforts made to keep this integration up-to-date.

**Comment by jasonmgeorge** [comment]
Hi @alvinyu2003, the latest release is updated to version 202310.1.3 of the OneTrust SDK. Thank you!
