### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by Magiic** [mparticle-integrations/mparticle-apple-integration-onetrust#6]
Hello, can you add Swift Package Manager to integrate this sdk via Apple's dependency manager? Thank you.

**Comment by pjcau** [comment]
Hi Guys, 

that's really important for all in the Apple community.

Thank you

Jonny

**Comment by Subhanc** [comment]
Hello, has this been any update on this request? Would be very useful for our SPM migration.

**Comment by einsteinx2** [comment]
Apologies for the delay on this, SPM support has been added to the latest release version 8.0.6
